# Generated by Django 5.0.8 on 2024-08-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_parametertypeunit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="toolmodule",
            old_name="status",
            new_name="logical_status",
        ),
        migrations.AddField(
            model_name="toolmodule",
            name="odoo_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="toolmodule",
            name="physical_status",
            field=models.TextField(blank=True, null=True),
        ),
    ]
