name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: 172.20.10.6
          username: rndadmin
          key: 33gf7svj8Vozp68V
          port: 22
      - name: Pull Changes on Server
        run: |
          git pull

      - name: Build Frontend
        run: |
          cd tgt_practice_frontend/
          npm run build
          cp -r dist/ ../tgt_practice_backend/nginx
          cd ..

      - name: Restart Docker
        run: |
          sudo docker compose up -d --build
